spring.application.name=Airline Reservation System

# MySQL Configuration
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:airline_reservation}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Inngest Configuration
inngest.app-id=${INNGEST_APP_ID:airline-reservation-system}

# Stripe Configuration
stripe.api-key=${STRIPE_API_KEY}
stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET}
stripe.product-name=${STRIPE_PRODUCT_NAME:Airline Reservation}
